# Basic Python

## 1. Split this string

In [4]:
s = "Hi there Sam!"
s=s.split(" ")
print(s)

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [5]:
planet = "Earth"
diameter = 12742
print("The diameter of {} is {} kilometers".format("Earth",12742))

The diameter of Earth is 12742 kilometers


## 3. In this nest dictionary grab the word "hello"

In [10]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print("hello")

hello


# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [6]:
np=[0]*10
print(np)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [9]:
np=[5]*10
print(np)

[5, 5, 5, 5, 5, 5, 5, 5, 5, 5]


## 5. Create an array of all the even integers from 20 to 35

In [10]:
arr=[]
for i in range(20,36):
   arr.append(i)
print(arr)

[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [3]:
import numpy as np
arr=np.arange(0,9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [13]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
final=a,b
print(final)

(array([1, 2, 3]), array([4, 5, 6]))


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [2]:
import pandas as pd
data={
    "Name":["Aravind","Mani","Karthi"],
    "Grade" :[1,2,3]
}
data_frame=pd.DataFrame(data)
print(data_frame)

      Name  Grade
0  Aravind      1
1     Mani      2
2   Karthi      3


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [5]:
for i in range(1,32):
  print(i,"jan, 2023")
for j in range(1,11):
  print(j,"Feb, 2023")

1 jan, 2023
2 jan, 2023
3 jan, 2023
4 jan, 2023
5 jan, 2023
6 jan, 2023
7 jan, 2023
8 jan, 2023
9 jan, 2023
10 jan, 2023
11 jan, 2023
12 jan, 2023
13 jan, 2023
14 jan, 2023
15 jan, 2023
16 jan, 2023
17 jan, 2023
18 jan, 2023
19 jan, 2023
20 jan, 2023
21 jan, 2023
22 jan, 2023
23 jan, 2023
24 jan, 2023
25 jan, 2023
26 jan, 2023
27 jan, 2023
28 jan, 2023
29 jan, 2023
30 jan, 2023
31 jan, 2023
1 Feb, 2023
2 Feb, 2023
3 Feb, 2023
4 Feb, 2023
5 Feb, 2023
6 Feb, 2023
7 Feb, 2023
8 Feb, 2023
9 Feb, 2023
10 Feb, 2023


import ## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [3]:
import pandas as pd

lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
data_frame=pd.DataFrame(lists)
print(data_frame)


   0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24
